apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- grafana/
- influxdb/
images:
- name: influxdb
  newTag: "2.8"
- name: grafana/grafana
  newTag: 12.3.0
